import { Vessel } from "@/types/vessel";

// Realistic test vessels — based on publicly reported deployments and known positions
// All data reflects publicly announced deployments, NOT classified intel
export const TEST_VESSELS: Vessel[] = [

  // ── US Navy / MSC — Middle East ──────────────────────────────
  {
    mmsi: "369970260",
    name: "USS DWIGHT D EISENHOWER",
    callsign: "NAVY1",
    shipType: 35,
    latitude: 12.8,
    longitude: 43.5,
    speed: 14,
    course: 340,
    heading: 340,
    navStatus: 0,
    destination: "5TH FLEET AOR",
    isMilitary: true,
    country: "US",
    navy: "us",
    vesselCategory: "carrier",
    lastUpdate: Date.now(),
    region: "middle-east",
  },
  {
    mmsi: "338234501",
    name: "USNS SUPPLY",
    callsign: "MSC1",
    shipType: 35,
    latitude: 26.1,
    longitude: 55.8,
    speed: 8,
    course: 180,
    heading: 180,
    navStatus: 0,
    destination: "MANAMA",
    isMilitary: true,
    country: "US",
    navy: "us",
    vesselCategory: "supply",
    lastUpdate: Date.now(),
    region: "middle-east",
  },
  {
    mmsi: "338910234",
    name: "USS GRAVELY",
    callsign: "DDG107",
    shipType: 35,
    latitude: 15.2,
    longitude: 42.4,
    speed: 18,
    course: 15,
    heading: 15,
    navStatus: 0,
    destination: "RED SEA PATROL",
    isMilitary: true,
    country: "US",
    navy: "us",
    vesselCategory: "destroyer",
    lastUpdate: Date.now(),
    region: "middle-east",
  },
  {
    mmsi: "338812345",
    name: "USS LABOON",
    callsign: "DDG58",
    shipType: 35,
    latitude: 13.9,
    longitude: 44.1,
    speed: 15,
    course: 200,
    heading: 200,
    navStatus: 0,
    destination: "GULF OF ADEN",
    isMilitary: true,
    country: "US",
    navy: "us",
    vesselCategory: "destroyer",
    lastUpdate: Date.now(),
    region: "middle-east",
  },
  {
    mmsi: "338456789",
    name: "USNS PATUXENT",
    callsign: "MSC2",
    shipType: 35,
    latitude: 24.5,
    longitude: 57.2,
    speed: 6,
    course: 90,
    heading: 90,
    navStatus: 0,
    destination: "ARABIAN SEA",
    isMilitary: true,
    country: "US",
    navy: "us",
    vesselCategory: "supply",
    lastUpdate: Date.now(),
    region: "middle-east",
  },

  // ── UK Royal Navy / RFA — Middle East ─────────────────────────
  {
    mmsi: "232004567",
    name: "HMS DIAMOND",
    callsign: "GBHD",
    shipType: 35,
    latitude: 22.1,
    longitude: 38.5,
    speed: 20,
    course: 170,
    heading: 170,
    navStatus: 0,
    destination: "GULF OF ADEN",
    isMilitary: true,
    country: "GB",
    navy: "uk",
    vesselCategory: "destroyer",
    lastUpdate: Date.now(),
    region: "middle-east",
  },
  {
    mmsi: "235012345",
    name: "RFA TIDEFORCE",
    callsign: "GBTF",
    shipType: 35,
    latitude: 23.4,
    longitude: 58.8,
    speed: 10,
    course: 280,
    heading: 280,
    navStatus: 0,
    destination: "BAHRAIN",
    isMilitary: true,
    country: "GB",
    navy: "uk",
    vesselCategory: "supply",
    lastUpdate: Date.now(),
    region: "middle-east",
  },

  // ── Russian Navy — Arabian Sea / Indian Ocean ─────────────────
  {
    mmsi: "273345678",
    name: "RFS ADMIRAL GORSHKOV",
    callsign: "RUAG",
    shipType: 35,
    latitude: 18.5,
    longitude: 62.0,
    speed: 16,
    course: 225,
    heading: 225,
    navStatus: 0,
    destination: "ARABIAN SEA",
    isMilitary: true,
    country: "RU",
    navy: "russia",
    vesselCategory: "frigate",
    lastUpdate: Date.now(),
    region: "middle-east",
  },

  // ── Indian Navy — Arabian Sea ──────────────────────────────────
  {
    mmsi: "419012345",
    name: "INS VISAKHAPATNAM",
    callsign: "INVP",
    shipType: 35,
    latitude: 14.2,
    longitude: 52.8,
    speed: 18,
    course: 45,
    heading: 45,
    navStatus: 0,
    destination: "ARABIAN SEA PATROL",
    isMilitary: true,
    country: "IN",
    navy: "india",
    vesselCategory: "destroyer",
    lastUpdate: Date.now(),
    region: "middle-east",
  },
  {
    mmsi: "419056789",
    name: "INS TRIKAND",
    callsign: "INTK",
    shipType: 35,
    latitude: 12.1,
    longitude: 47.5,
    speed: 14,
    course: 300,
    heading: 300,
    navStatus: 0,
    destination: "GULF OF ADEN",
    isMilitary: true,
    country: "IN",
    navy: "india",
    vesselCategory: "frigate",
    lastUpdate: Date.now(),
    region: "middle-east",
  },

  // ── US Navy — Europe / Mediterranean ──────────────────────────
  {
    mmsi: "338667890",
    name: "USS HARRY S TRUMAN",
    callsign: "CVN75",
    shipType: 35,
    latitude: 36.5,
    longitude: 20.2,
    speed: 12,
    course: 90,
    heading: 90,
    navStatus: 0,
    destination: "MEDITERRANEAN",
    isMilitary: true,
    country: "US",
    navy: "us",
    vesselCategory: "carrier",
    lastUpdate: Date.now(),
    region: "europe",
  },

  // ── US Navy — Pacific ──────────────────────────────────────────
  {
    mmsi: "338445566",
    name: "USS RONALD REAGAN",
    callsign: "CVN76",
    shipType: 35,
    latitude: 22.5,
    longitude: 122.8,
    speed: 14,
    course: 60,
    heading: 60,
    navStatus: 0,
    destination: "WESTERN PACIFIC",
    isMilitary: true,
    country: "US",
    navy: "us",
    vesselCategory: "carrier",
    lastUpdate: Date.now(),
    region: "pacific",
  },

  // ── China PLAN — Pacific ───────────────────────────────────────
  {
    mmsi: "412334455",
    name: "CNS LIAONING",
    callsign: "PLAN1",
    shipType: 35,
    latitude: 24.8,
    longitude: 122.5,
    speed: 16,
    course: 120,
    heading: 120,
    navStatus: 0,
    destination: "WESTERN PACIFIC",
    isMilitary: true,
    country: "CN",
    navy: "china",
    vesselCategory: "carrier",
    lastUpdate: Date.now(),
    region: "pacific",
  },

  // ── US Navy — US Waters ────────────────────────────────────────
  {
    mmsi: "338123456",
    name: "USS GERALD R FORD",
    callsign: "CVN78",
    shipType: 35,
    latitude: 36.9,
    longitude: -76.3,
    speed: 0,
    course: 0,
    heading: 180,
    navStatus: 1,
    destination: "NORFOLK VA",
    isMilitary: true,
    country: "US",
    navy: "us",
    vesselCategory: "carrier",
    lastUpdate: Date.now(),
    region: "us",
  },
];
