import { Aircraft } from "@/types/flight";

// Realistic test data — based on publicly reported aircraft types and flight patterns
export const TEST_AIRCRAFT: Aircraft[] = [
  // ── United States ─────────────────────────────────────────────
  {
    icao24: "ae1234",
    callsign: "RCH224",
    origin_country: "United States",
    time_position: Date.now() / 1000,
    last_contact: Date.now() / 1000,
    longitude: -80.5,
    latitude: 36.2,
    baro_altitude: 10670,
    on_ground: false,
    velocity: 245,
    true_track: 270,
    vertical_rate: 0,
    sensors: null,
    geo_altitude: 10700,
    squawk: "7777",
    spi: false,
    position_source: 0,
    isMilitary: true,
    aircraftType: "transport",
    region: "us",
  },
  {
    icao24: "ae5678",
    callsign: "JAKE11",
    origin_country: "United States",
    time_position: Date.now() / 1000,
    last_contact: Date.now() / 1000,
    longitude: -97.3,
    latitude: 33.5,
    baro_altitude: 9144,
    on_ground: false,
    velocity: 210,
    true_track: 90,
    vertical_rate: -3,
    sensors: null,
    geo_altitude: 9200,
    squawk: "5441",
    spi: false,
    position_source: 0,
    isMilitary: true,
    aircraftType: "tanker",
    region: "us",
  },
  {
    icao24: "ae2233",
    callsign: "GHOST31",
    origin_country: "United States",
    time_position: Date.now() / 1000,
    last_contact: Date.now() / 1000,
    longitude: -117.1,
    latitude: 33.2,
    baro_altitude: 3048,
    on_ground: false,
    velocity: 180,
    true_track: 200,
    vertical_rate: -8,
    sensors: null,
    geo_altitude: 3100,
    squawk: "0000",
    spi: false,
    position_source: 0,
    isMilitary: true,
    aircraftType: "fighter",
    region: "us",
  },

  // ── Middle East ─────────────────────────────────────────────────
  // US E-3 AWACS doing orbits over the Persian Gulf (common)
  {
    icao24: "ae9abc",
    callsign: "MAGIC41",
    origin_country: "United States",
    time_position: Date.now() / 1000,
    last_contact: Date.now() / 1000,
    longitude: 50.5,
    latitude: 26.2,
    baro_altitude: 9754,
    on_ground: false,
    velocity: 220,
    true_track: 180,
    vertical_rate: 0,
    sensors: null,
    geo_altitude: 9800,
    squawk: "1234",
    spi: false,
    position_source: 0,
    isMilitary: true,
    aircraftType: "surveillance",
    region: "middle-east",
  },
  // USAF C-17 transport heading toward Al Udeid Air Base (Qatar)
  {
    icao24: "ae3def",
    callsign: "REACH701",
    origin_country: "United States",
    time_position: Date.now() / 1000,
    last_contact: Date.now() / 1000,
    longitude: 45.2,
    latitude: 30.1,
    baro_altitude: 11000,
    on_ground: false,
    velocity: 260,
    true_track: 135,
    vertical_rate: -5,
    sensors: null,
    geo_altitude: 11050,
    squawk: "3310",
    spi: false,
    position_source: 0,
    isMilitary: true,
    aircraftType: "transport",
    region: "middle-east",
  },
  // RC-135 Rivet Joint SIGINT orbit over Syria/Iraq border (regularly tracked)
  {
    icao24: "ae4f01",
    callsign: "RIVET22",
    origin_country: "United States",
    time_position: Date.now() / 1000,
    last_contact: Date.now() / 1000,
    longitude: 40.8,
    latitude: 34.5,
    baro_altitude: 10668,
    on_ground: false,
    velocity: 215,
    true_track: 350,
    vertical_rate: 0,
    sensors: null,
    geo_altitude: 10720,
    squawk: "4405",
    spi: false,
    position_source: 0,
    isMilitary: true,
    aircraftType: "surveillance",
    region: "middle-east",
  },
  // KC-135 tanker orbit over Red Sea (supports F-35 ops in the region)
  {
    icao24: "ae7c22",
    callsign: "SHELL41",
    origin_country: "United States",
    time_position: Date.now() / 1000,
    last_contact: Date.now() / 1000,
    longitude: 36.8,
    latitude: 22.4,
    baro_altitude: 7620,
    on_ground: false,
    velocity: 195,
    true_track: 10,
    vertical_rate: 0,
    sensors: null,
    geo_altitude: 7680,
    squawk: "4430",
    spi: false,
    position_source: 0,
    isMilitary: true,
    aircraftType: "tanker",
    region: "middle-east",
  },
  // Israeli Air Force — IAF frequently appears over eastern Mediterranean
  {
    icao24: "738a1c",
    callsign: "IAF101",
    origin_country: "Israel",
    time_position: Date.now() / 1000,
    last_contact: Date.now() / 1000,
    longitude: 34.9,
    latitude: 31.8,
    baro_altitude: 8534,
    on_ground: false,
    velocity: 310,
    true_track: 270,
    vertical_rate: 0,
    sensors: null,
    geo_altitude: 8600,
    squawk: "2251",
    spi: false,
    position_source: 0,
    isMilitary: true,
    aircraftType: "fighter",
    region: "middle-east",
  },
  // IAF transport (C-130J) heading north — common pattern
  {
    icao24: "739f44",
    callsign: "IAF440",
    origin_country: "Israel",
    time_position: Date.now() / 1000,
    last_contact: Date.now() / 1000,
    longitude: 35.2,
    latitude: 32.1,
    baro_altitude: 6096,
    on_ground: false,
    velocity: 175,
    true_track: 15,
    vertical_rate: 12,
    sensors: null,
    geo_altitude: 6150,
    squawk: "3377",
    spi: false,
    position_source: 0,
    isMilitary: true,
    aircraftType: "transport",
    region: "middle-east",
  },
  // RAF Voyager tanker out of Akrotiri (Cyprus) — routine ME presence
  {
    icao24: "43c8f0",
    callsign: "COMET11",
    origin_country: "United Kingdom",
    time_position: Date.now() / 1000,
    last_contact: Date.now() / 1000,
    longitude: 33.1,
    latitude: 34.6,
    baro_altitude: 9144,
    on_ground: false,
    velocity: 230,
    true_track: 120,
    vertical_rate: 0,
    sensors: null,
    geo_altitude: 9200,
    squawk: "0552",
    spi: false,
    position_source: 0,
    isMilitary: true,
    aircraftType: "tanker",
    region: "middle-east",
  },
  // Saudi RSAF F-15SA patrol over Saudi airspace
  {
    icao24: "710c44",
    callsign: "RSAF11",
    origin_country: "Saudi Arabia",
    time_position: Date.now() / 1000,
    last_contact: Date.now() / 1000,
    longitude: 44.1,
    latitude: 24.8,
    baro_altitude: 7620,
    on_ground: false,
    velocity: 350,
    true_track: 220,
    vertical_rate: 0,
    sensors: null,
    geo_altitude: 7700,
    squawk: "5500",
    spi: false,
    position_source: 0,
    isMilitary: true,
    aircraftType: "fighter",
    region: "middle-east",
  },
  // UAE AF C-17 operating out of Al Dhafra
  {
    icao24: "896102",
    callsign: "UAEAF1",
    origin_country: "United Arab Emirates",
    time_position: Date.now() / 1000,
    last_contact: Date.now() / 1000,
    longitude: 54.4,
    latitude: 24.2,
    baro_altitude: 5486,
    on_ground: false,
    velocity: 220,
    true_track: 310,
    vertical_rate: 15,
    sensors: null,
    geo_altitude: 5540,
    squawk: "6601",
    spi: false,
    position_source: 0,
    isMilitary: true,
    aircraftType: "transport",
    region: "middle-east",
  },
  // US MQ-9 Reaper ISR orbit over Eastern Mediterranean / Syria
  {
    icao24: "ae6610",
    callsign: "REAPER9",
    origin_country: "United States",
    time_position: Date.now() / 1000,
    last_contact: Date.now() / 1000,
    longitude: 37.4,
    latitude: 36.1,
    baro_altitude: 8534,
    on_ground: false,
    velocity: 140,
    true_track: 90,
    vertical_rate: 0,
    sensors: null,
    geo_altitude: 8600,
    squawk: "4461",
    spi: false,
    position_source: 0,
    isMilitary: true,
    aircraftType: "surveillance",
    region: "middle-east",
  },

  // ── Europe ────────────────────────────────────────────────────
  {
    icao24: "ae6789",
    callsign: "VIPER21",
    origin_country: "United States",
    time_position: Date.now() / 1000,
    last_contact: Date.now() / 1000,
    longitude: 13.4,
    latitude: 52.5,
    baro_altitude: 7620,
    on_ground: false,
    velocity: 280,
    true_track: 315,
    vertical_rate: 10,
    sensors: null,
    geo_altitude: 7680,
    squawk: "0042",
    spi: false,
    position_source: 0,
    isMilitary: true,
    aircraftType: "fighter",
    region: "europe",
  },
  {
    icao24: "43c901",
    callsign: "ASCOT852",
    origin_country: "United Kingdom",
    time_position: Date.now() / 1000,
    last_contact: Date.now() / 1000,
    longitude: -1.8,
    latitude: 51.5,
    baro_altitude: 10060,
    on_ground: false,
    velocity: 240,
    true_track: 95,
    vertical_rate: 0,
    sensors: null,
    geo_altitude: 10100,
    squawk: "1551",
    spi: false,
    position_source: 0,
    isMilitary: true,
    aircraftType: "transport",
    region: "europe",
  },

  // ── Pacific ───────────────────────────────────────────────────
  {
    icao24: "ae0011",
    callsign: "RIVET01",
    origin_country: "United States",
    time_position: Date.now() / 1000,
    last_contact: Date.now() / 1000,
    longitude: 128.0,
    latitude: 35.0,
    baro_altitude: 12000,
    on_ground: false,
    velocity: 230,
    true_track: 0,
    vertical_rate: 0,
    sensors: null,
    geo_altitude: 12050,
    squawk: "4401",
    spi: false,
    position_source: 0,
    isMilitary: true,
    aircraftType: "surveillance",
    region: "pacific",
  },
];
